#端口号
server:
  port: 8082
#服务名称
spring:
  application:
    name: redis_test
#mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/bz_shop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #整合redis
  redis:
    database: 0  #redis库的名字,默认是0库
    host: 127.0.0.1
    port: 6379
    jedis:
        pool:
          max-active: 200 #最大连接数
          max-wait: -1 #连接池最大等待时间(负数表示没有限制)
          max-idle: 10 #连接池最大空闲数
          min-idle: 0 #连接池最小空闲数
    timeout: 2000 #连接超时时间
#插件mybatislog自动拼接在控制台打印
mybatis:
  type-aliases-package: com.bjsxt.pojo   #起别名
  mapper-locations: classpath:/com/bjsxt/mapper/*.xml  #mapper.xml在的位置
  #config-location: classpath:mybatis/mybatis-config.xml  # 加载全局的配置文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatislog插件控制台输出,拼接我们想要的sql
#控制台日志打印
logging:
  level:
    com.bjsxt.mapper: debug